apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qlrr2wzye-go 
  janus-idp.io/tekton: qlrr2wzye-go
  backstage.io/kubernetes-id: qlrr2wzye-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qlrr2wzye-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml